#include "o2/stdafx.h"
#include <gtest/gtest.h>

#include "Scene/SceneTestHelpers.h"
#include "ZeroLine/GameJsBridge.h"
#include "ZeroLine/ZeroLineBootstrap.h"
#include "ZeroLine/ZeroLineHost.h"
#include "o2/Assets/Assets.h"
#include "o2/Scene/Actor.h"
#include "o2/Scene/CameraActor.h"
#include "o2/Scene/Components/ScriptableComponent.h"
#include "o2/Scene/Scene.h"
#include "o2/Scripts/ScriptEngine.h"
#include "o2/Utils/FileSystem/FileSystem.h"

using namespace o2;

// The bootstrap scene is generated by this test into Assets/Bootstrap.scn (the editor
// opens it, the game loads its built copy) and must boot the game when loaded back
TEST(ZeroLineScene, BootstrapSceneRegeneratesAndBootsTheGame)
{
    zero_line::RegisterGameJsApi();

    String path;
    {
        SceneCleanGuard sceneGuard;
        auto game = zero_line::BuildBootstrapScene();
        ASSERT_TRUE(game);
        EXPECT_TRUE(game->GetComponent<ZeroLineHost>());
        EXPECT_TRUE(game->GetComponent<ScriptableComponent>());

        if (o2FileSystem.IsFolderExist(o2Assets.GetAssetsPath()))
        {
            path = o2Assets.GetAssetsPath() + "Bootstrap.scn";
            zero_line::SaveBootstrapScene(path);
        }
    }

    if (path.IsEmpty())
        GTEST_SKIP() << "no source assets folder next to the binaries";

    ASSERT_TRUE(o2FileSystem.IsFileExist(path));

    SceneCleanGuard sceneGuard;
    o2Scene.Load(path);
    TickFrames(3, 0.016f);

    auto game = o2Scene.FindActor("Game");
    ASSERT_TRUE(game);
    EXPECT_TRUE(game->GetComponent<ZeroLineHost>());
    EXPECT_TRUE(game->GetComponent<ScriptableComponent>());
    EXPECT_TRUE(DynamicCast<CameraActor>(o2Scene.FindActor("ui camera")));

    auto state = o2Scripts.Eval("ZL.game.state");
    ASSERT_EQ(state.GetValueType(), ScriptValue::ValueType::String);
    EXPECT_EQ((String)state, "playing");
    EXPECT_EQ((float)o2Scripts.Eval("ZL.game.view.CountTiles()"), 25.0f);
}
