// Built-in reference for the AI agent, read on demand with the read_guide tool.
//
// This is the knowledge that is expensive to rediscover and too big for the
// system prompt (which is re-sent on every step): engine and project specifics
// distilled from o2/Docs and the sources. Anything deeper the agent looks up
// itself with search_engine / read_engine_file.

var AI_GUIDES = {};

AI_GUIDES.project = [
    'This is a project built on the o2 engine, opened in the web editor. Game logic is C++ (Sources/Game builds',
    'GameLib, Sources/Editor builds the editor extensions); content lives in Assets/ and is what you can change.',
    '',
    'Read the actual Assets/ layout with list_files before assuming anything - every project arranges it differently.',
    'Typical entries: scenes (.scn), prototypes (.proto), textures, atlases (.atlas), fonts, sounds, particles,',
    'localization and Scripts/ with the JavaScript logic of UI windows.',
    '',
    'The C++/JS split for UI windows: a window prototype carries an o2::ScriptableComponent whose mScript points at a',
    '.js asset. C++ creates the window, pushes values onto the script instance (SetScriptProperty -> a property on the',
    'JS object, e.g. coins) and injects an `action` callback; the script calls that callback to report button presses',
    'back to C++. So gameplay reactions live in C++, window behaviour in JS.',
    '',
    'What is yours and what is not: Assets/ is a private copy of the project for this browser session - read and write',
    'it freely, nobody else sees it. The engine checkout (o2/Docs, o2/Framework/Sources, o2/Editor/Sources,',
    'o2/AssetsBuildTool, Sources) is shared and read-only reference material: search_engine / read_engine_file only.',
    'You cannot compile C++ from here; changing engine or game sources is out of scope - work through assets, scripts',
    'and the editor UI.',
].join('\n');

AI_GUIDES.assets = [
    'Asset file formats (verified against the project files).',
    '',
    'A scene (.scn) has four top-level keys: Layers ([{mName}]), DefaultLayer, Tags, Actors. Root actors are',
    'polymorphic: {"Type": <class>, "Value": {...}}. Abridged example:',
    '  {"Layers":[{"mName":"Default"}],"DefaultLayer":"Default","Tags":null,',
    '   "Actors":[{"Type":"o2::Actor","Value":{"Id":77400000000000001,"mName":"GameBootstrap",',
    '     "Transform":{"position":{"x":0.0,"y":0.0},"size":{"x":10.0,"y":10.0},"pivot":{"x":0.5,"y":0.5}},',
    '     "Components":[{"Type":"GameBootstrapComponent","Data":{"mId":77400000000000002}}]}}]}',
    '',
    'Inside an actor: Id (UInt64 scene uid), mName, Transform, Components, Children. Components and children are',
    '{"Type": <class>, "Data": {...}} - note Type/Data here versus Type/Value for the root refs. Children nest the same',
    'body recursively. Every component carries its own mId. Plain actors use position/size/scale/pivot/eulerAngles/shear;',
    'widget actors (o2::Widget, Button, Label) use anchorMin/anchorMax/offsetMin/offsetMax plus InternalWidgets/Layers/States.',
    '',
    'A prototype (.proto) is an ActorAsset: one key mActor holding a single {"Type","Value"} actor node. A prefab derived',
    'from another prefab is stored as a DELTA - only fields that differ from the base are written - and carries',
    '"Prototype":{"id":<uid>,"path":"Prefabs/Base.proto"} plus "PrototypeLink":<Id of the matching node in the base>.',
    'A standalone prefab has neither key.',
    '',
    'Field naming: reflected C++ members keep their names verbatim, m-prefix included (mName, mColor, mImageAsset, mId);',
    'hand-written keys have no prefix (Id, Transform, Components, Children, Type, Data, Value, Prototype, PrototypeLink).',
    'Values equal to the default (or, in a delta, equal to the base) are omitted - a missing key means "default" in a raw',
    'node and "inherit" in a delta node, so deleting a key is not the same as resetting it.',
    '',
    'References: an asset ref is {"id": <32-hex uid>, "path": <path under Assets>} - the id wins, the path is a fallback.',
    'A scene-object ref is {"ID": <uid>} for an actor and {"ActorID": <uid>, "ComponentId": <uid>} for a component.',
    '',
    'How to corrupt the project by hand, so you avoid it: changing an asset uid, or moving a file without its .meta,',
    'invalidates every id pointing at it (only refs whose path still matches survive) - for a Prototype ref this silently',
    'turns the instance into its sparse delta, i.e. a nearly empty actor. Editing Id/mId in a base prefab breaks the',
    'PrototypeLink lookups of everything derived from it. Ids must stay unique inside a file; when adding an actor by',
    'hand invent a fresh large random integer instead of copying one. Type must be a registered reflection name, or the',
    'component is dropped with "Can\'t create component by type X" in the log.',
    '',
    '.meta files: every asset and folder has a sibling <name>.<ext>.meta holding {"Type": <asset class>, "Value":',
    '{"mId": <32-hex uid>}} plus per-type extras (ImageAsset::Meta has atlasId and optional sliceBorder). A missing .meta',
    'is regenerated on the next rebuild with a NEW uid - which breaks existing references - so when you create an asset by',
    'hand either write its .meta with a fresh uid or accept the generated one immediately; when moving or renaming, move',
    'the .meta along and never change its mId; when deleting, delete both.',
    '',
    'Not every file under Assets ends up in BuiltAssets: some folders are simply not part of the build (Particles/ is one',
    'of them in this project). A reference to an unbuilt asset loads as nothing, with at most one line in the log - so',
    'when you pick an existing asset to reference, prefer one the game already uses, and check read_log afterwards.',
    '',
    'If an asset or a scene suddenly fails to load although its source file is fine, the built copy went missing while',
    'the build index still lists it, and an incremental build cannot heal that: run rebuild_assets({force:true}).',
    '',
    'Rebuild: the editor loads asset CONTENT from BuiltAssets, not from Assets, so a hand edit takes effect only after',
    'rebuild_assets. The rebuild is incremental (keyed by uid and edit time), regenerates BuiltAssets/<platform>/Data,',
    'repacks atlases, and writes page data back into the source .atlas files - so .atlas files showing as changed after a',
    'rebuild is normal, not your doing. An already open scene may keep the old content: reopen it if a change does not show.',
    '',
    'Deeper detail: o2/Docs/en/Architecture/LowLevel/assets.md, o2/Docs/en/Architecture/Utils/serialization.md,',
    'o2/Docs/en/Architecture/HighLevel/scene.md; sources o2/Framework/Sources/o2/Scene/Actor.cpp (the exact key set),',
    'o2/Framework/Sources/o2/Assets/AssetRef.h (refs), o2/AssetsBuildTool/Sources/o2AssetBuilder/AssetsBuilder.cpp (rebuild).',
].join('\n');

AI_GUIDES.editor = [
    'The o2 editor as the user sees it on screen (you drive it with click/type_text/press_key/screenshot).',
    '',
    'Default layout: top menu bar (File, Edit, View, Run, Help, Debug); under it the playback panel (Play, frame step,',
    'game speed) and the tools panel; left the Tree window (scene hierarchy); centre the Scene view; right Properties',
    '(with a Game tab next to it); the bottom dock holds Log, Animation and Assets as tabs.',
    '',
    'Two modes: edit mode (the scene is static, editable, saveable) and play mode (the scene updates, input goes to the',
    'Game window, saving is disabled). Play/stop is P, frame step Ctrl+P, speed Ctrl+plus / Ctrl+minus, also in the Run menu.',
    'Undo is Ctrl+Z and redo Ctrl+Y (Edit menu). Hotkeys act on the focused window, so click the window first.',
    '',
    'Tree window: one row per actor, name editable by double-click, a filled dot means enabled, a chain icon means the',
    'actor came from a prototype (clicking it highlights that prototype in Assets). Right-click opens the context menu,',
    'which is also where new actors are created (Create empty actor, or a type from the Create submenu). Actors are',
    'reparented by drag and drop. A second mode shows draw order instead of hierarchy.',
    '',
    'Properties window: shows the selected object - its name, enabled state, transform, then one block per component,',
    'with a cross to remove a component and an Add component menu at the bottom that filters by name.',
    '',
    'Assets window: folder tree on the left, asset icons on the right. Double-click an icon opens the asset by type -',
    'a scene opens in the editor, a prototype is instantiated into the current scene, a .js opens in a text editor, and',
    'anything else is shown in Properties. Double-click the NAME label instead and it starts renaming.',
    'Reliability note when you drive this by clicking: the first click on a not-yet-selected asset can trigger a slow',
    'Properties rebuild that eats the double-click window, so click once to select, wait about a second, then double-click.',
    '',
    'What you can and cannot drive: the editor chrome (menus, Assets, Tree, Properties) does not react to synthetic',
    'clicks at all - never spend steps trying. Editor work is done with the tools: open_scene, save_scene,',
    'rebuild_assets, play_mode, the file tools, and run_script for everything else.',
    'click/type_text/press_key exist only for playing the running game inside the Game window, with play mode on.',
    '',
    'Seeing the scene: scene_tree returns the hierarchy with paths, types, enabled state, position/size/scale/angle,',
    'the world rectangle, widget layout (anchorMin/anchorMax/offsetMin/offsetMax) and component types. view_info returns',
    'the canvas size, whether play mode is on, the Game window rectangle and the game camera, plus the formula that',
    'turns a world position into a canvas pixel. Aim clicks from those numbers - a screenshot is for judging looks,',
    'not for measuring coordinates.',
    '',
    'run_script runs JavaScript inside the engine immediately, with no script asset and no play mode: sceneRoots holds',
    'the root actors, findActor("Name/Child") walks by path, eachActor(fn) visits everything, and the o2 namespace has',
    'the bound engine types. Your code runs inside a function, so return a value to see it. Use it to inspect and',
    'change actors and components, and to script editor work the tools do not cover; save_scene writes the result.',
    '',
    'Coordinates: screenshot() returns the editor canvas at half size; click coordinates are full-size canvas pixels,',
    'so double what you measure on the image. Origin is the top-left corner of the canvas.',
    '',
    'Deeper detail: o2/Docs/en/Editor/editor.md and the per-window pages under o2/Docs/en/Editor/.',
].join('\n');

AI_GUIDES.workflows = [
    'Recipes for the usual jobs. Work in three phases - gather what you need, plan the whole change, then apply it in',
    'one batch - instead of a long chain of small moves with a rebuild between each.',
    '',
    'Before writing engine-specific code, read the guide for it. Guessing an API costs several failed calls plus the',
    'steps spent reading the errors; the guide costs one call and states what is verified.',
    '',
    'When you set up a test scene, open that exact scene before play_mode and confirm with view_info (it reports',
    'openScene). Looking for your object in whatever scene happened to be open is a classic way to lose ten steps.',
    '',
    '',
    'Change the behaviour of a UI window: search_files for the class name to find its script under Scripts/, read the',
    'window you need with read_file, change it with edit_file, then rebuild_assets once, then read_log to check for',
    'script or build errors.',
    '',
    'Retune a prefab (size, image, physics): search_files for the prefab name, read the .proto, edit the exact field.',
    'Remember it may be a delta over a base prefab: if the field you want is absent, it is inherited - add the key rather',
    'than looking for it elsewhere, and never touch Id/PrototypeLink numbers.',
    '',
    'Put a prototype on the scene: edit the .scn by hand - add an actor node carrying "Prototype" (the asset ref of the',
    '.proto) and a fresh unique Id. You cannot do it by clicking, since the editor windows ignore synthetic input.',
    '',
    'See it run: after rebuild_assets, call play_mode({on:true}), wait a second or two, take a screenshot to check the',
    'result, then play_mode({on:false}). Scripts only tick in play mode, so this is the only way to observe OnStart,',
    'Update or particle effects at all.',
    '',
    'Create a new asset by hand: write the file with write_file, then rebuild_assets - the builder generates the missing',
    '.meta with a fresh uid. Reference it from other assets only after that, using the uid the builder assigned',
    '(read the generated .meta to learn it).',
    '',
    'Verify your work: read_log first (it carries build errors and script exceptions verbatim), then a screenshot if the',
    'change is visual. Reading a file back after edit_file is usually pointless - the tool already reported the result.',
    '',
    'Batch discipline: rebuild_assets takes 10-20 seconds and freezes the editor, so make all file changes first and',
    'rebuild once at the end, not after every edit.',
].join('\n');

AI_GUIDES.scripting = [
    'JavaScript scripting in o2 (every name below is verified in the engine sources).',
    '',
    'Read this first if you are writing a UI window script: C++ injects a callback property named exactly `action` onto',
    'the instance, and the script reports presses with this.action("close"). A callback you name yourself is never called.',
    '',
    'A script is one .js asset attached to an actor by the C++ component o2::ScriptableComponent (in the editor:',
    'Add Component -> Basic -> Scriptable, then point its script property at the .js). Serialized it looks like',
    '  {"Type": "o2::ScriptableComponent", "Data": {"mScript": {"path": "Scripts/UI/WinWindow.js"}, "mId": 5979357506365508875}}',
    '',
    'HARD RULE: the class name must equal the file name, and the class must be a property of the JS global. The engine',
    'takes the class name from the file name and looks it up as an own property of the global; if it is missing it logs',
    "\"Can't find scripting class '<name>' in component file\". Hence the idiom used by every script in this project:",
    '  WinWindow = class WinWindow extends o2.Component { constructor() { super(); ... } }',
    'Bare assignment, no let/const - those never become global properties. Keep this exact form.',
    '',
    'o2.Component is a thin base (o2/Framework/Assets/Scripts/Component.js): class Component { _actor = {} }. Extending it',
    'only reserves the _actor slot; the constructor is called with no arguments and must call super().',
    '',
    'LIFECYCLE - exactly four members are ever called: OnStart(), OnEnabled(), OnDisabled(), Update(dt). The per-frame hook',
    'is Update, NOT OnUpdate; there is no OnDestroy, OnDraw, FixedUpdate or OnCollision - such a method is silently dead',
    'code. OnStart and Update only run in play mode (the editor does not tick the scene while merely editing);',
    'OnEnabled/OnDisabled fire on enable changes in either mode.',
    '',
    'Reaching the scene from a script: this._actor is the owning actor. Useful @SCRIPTABLE methods - FindChild(name)',
    '(recursive by name), GetChild("a/b/c") (by path), GetChildren, AddChild, RemoveChild, GetComponent, GetComponents,',
    'AddComponent, RemoveComponent, GetTransform, SetName/GetName, SetEnabled/Enable/Disable/IsEnabled, SetParent/GetParent,',
    'Destroy, AddToScene/RemoveFromScene/IsOnScene, SetLayer/GetLayer. A null reference arrives in JS as undefined, so guard:',
    '  let b = this._actor.FindChild("CloseButton"); if (b) { ... }',
    '',
    'GetComponent takes an exact type name string ("o2::ImageComponent" - no base-class matching), or a bound constructor',
    '(o2.ImageComponent, matched through reflection so bases work), or another script class - in that case you get the',
    'ScriptableComponent and .GetInstance() hands you that script\'s JS instance. That is the only verified script-to-script',
    'channel.',
    '',
    'Transform: this._actor.GetTransform() gives SetPosition2D/GetPosition2D, SetPositionX/Y, SetSize2D/GetSize2D,',
    'SetWidth/SetHeight, SetScale2D/GetScale2D, SetAngle/GetAngle (radians), SetAngleDegrees, SetPivot2D. Use the *2D',
    'variants: Vec3F has no JS converter, so the 3D overloads hand back an opaque wrapper with no .x/.y.',
    '',
    'Widgets: SetState(name, bool), GetState, SetTransparency, Show/Hide, Focus/Unfocus, GetChildWidget(path), AddLayer,',
    'FindLayer, SetLayoutDirty. Buttons expose an assignable onClick, which is how the project wires UI:',
    '  let self = this; let b = this._actor.FindChild("CloseButton"); if (b) b.onClick = function() { self.Emit("close"); };',
    'Labels have SetText/GetText/SetColor, images SetImageName/SetImageAsset, progress bars SetValue.',
    '',
    'Bound C++ types live on the o2 namespace object keyed by their C++ name (o2::Button -> o2.Button): new o2.Actor(1),',
    'new o2.Button(1). Math types are the exception: Vec2F/Vec2I arrive as the JS class Vec2 from',
    'o2/Framework/Assets/Scripts/Math.js (Rect, Border, Color4 and Math.randomBetween live there too). There is no',
    'o2.Vec2F - new o2.Vec2F(x, y) throws "o2.Vec2F is not a constructor" every time that line runs; use new Vec2(x, y).',
    '',
    'Moving an actor from a script, the verified way (do not guess variants of this - each wrong guess is a runtime',
    'error and a wasted step):',
    '  let t = actor.GetTransform();          // GetTransform is @SCRIPTABLE on Actor',
    '  t.SetPosition2D(new Vec2(x, y));       // Vec2 from Math.js, NOT o2.Vec2F',
    'Reading back is GetPosition2D(); sizes are SetSize2D/GetSize2D; angles SetAngleDegrees.',
    '',
    'Bindings cheat sheet, verified in the running editor:',
    '  new Vec2(x, y)                                  // math types come from Math.js, there is no o2.Vec2F',
    '  actor.GetTransform().SetPosition2D(new Vec2(x, y))',
    '  actor.GetComponent("o2::ImageComponent")        // exact type name, or a bound constructor',
    '  new o2.AssetRefActorAsset("UI/WinWindow.proto").Get().Instantiate()   // a prototype instance, from JS',
    '  new o2.Actor(1), new o2.Button(1)               // 1 = ActorCreateMode::NotInScene',
    'Asset ref types are named AssetRef<T> flattened, e.g. AssetRef<ActorAsset> -> o2.AssetRefActorAsset, and .Get()',
    'hands you the asset itself.',
    '',
    'What is NOT reachable from a script, so do not try: loading or looking up assets (there is no o2.Assets,',
    'no o2.AssetInfo.Load, no GetAssetId - assets are handled with the file tools instead), the filesystem',
    '(no require, no fs: run_script executes inside the engine in a browser tab), and anything without @SCRIPTABLE.',
    '',
    'Not every C++ method is reachable: only those marked @SCRIPTABLE. An emitter cannot be started from a script',
    '(Play is not scriptable) - put "mPlaying": true in the prototype instead. When a call silently does nothing, check',
    'the header for @SCRIPTABLE before assuming your logic is wrong.',
    '',
    'Talking to C++: there is no scene singleton in JS - everything goes through this._actor. C++ injects values and a',
    'callback onto the instance, and the names are fixed by the C++ side, so do not invent your own: GameWindow sets the',
    'properties coins, stars, soundOn, musicOn and a function property named exactly `action`. A window script reports a',
    'press with this.action("close") and must not declare its own action field - the injection overwrites it anyway, and a',
    'differently named callback is never called. Instance fields assigned in the constructor are serialized and editable in',
    'Properties - except names starting with _, which stay runtime-only.',
    '',
    'Logging: the global print(...) writes into the Scripting log stream, i.e. the editor Log window - read it with',
    'read_log. console.log goes to the browser devtools instead and you will not see it. Never Dump() or enumerate the',
    'global: under the browser backend the JS global is window itself and it recurses until the tab dies.',
    '',
    'Taking effect: the engine parses the BUILT copy of the script, so after editing you need rebuild_assets, and the',
    'instance is only created on deserialize or when the script property is set - so a running scene keeps the old body',
    'until it is reloaded.',
    '',
    'Deeper detail: o2/Docs/en/Architecture/LowLevel/scripting.md, o2/Docs/en/Architecture/HighLevel/components.md,',
    'o2/Framework/Sources/o2/Scene/Components/ScriptableComponent.cpp (the lifecycle dispatch),',
    'o2/Tests/Sources/Systems/ScriptSceneApiTest.cpp (working JS-facing examples).',
    'Live examples in this project: Assets/Scripts/UI/*.js with their C++ side Sources/GameLib/Windows/GameWindow.cpp.',
].join('\n');

AI_GUIDES.particles = [
    'The o2 particle system (verified in o2/Framework/Sources/o2/Render/Particles and .../Scene/Components).',
    '',
    'o2::ParticlesEmitterComponent IS the emitter (it inherits both Component and ParticlesEmitter), so all emitter',
    'fields serialize directly inside the component Data. Add it to an actor like any other component.',
    '',
    'TWO THINGS MAKE THE DIFFERENCE BETWEEN A WORKING EFFECT AND NOTHING AT ALL, and neither reports an error:',
    '1. The emitter is an animation and emits only while it is playing. Nothing starts it for you, and Play() is NOT',
    '   scriptable, so a script cannot start it either - you must write "mPlaying": true into the component data, plus',
    '   "mLoop": "Repeat" if the effect should keep going (the default Loop::None stops after mEmissionDuration).',
    '2. The particle image must exist in the BUILT assets. In this project Assets/Particles/** is NOT built - referencing',
    '   anything from there gives an empty effect and one line in the log: "Can\'t load image ...: unknown format".',
    '   Use an image the game actually ships, e.g. UI/StarGold.png, and confirm with read_log after play.',
    '',
    'Where to attach the emitter: put the components on a node that already has a working transform - the window widget',
    'itself, or an existing child. Several emitters on one node work fine. Creating fresh child nodes for them is what',
    'goes wrong: a bare o2::Actor child inside a widget hierarchy, or an o2::Widget child left with an empty layout,',
    'gets no size and no transform updates, and you get a blank screen with no error to explain it.',
    '',
    'There are no separate particle asset files in this project: an effect is entirely the component data inside the',
    'scene or prototype JSON. Searching for *.particle or similar finds nothing - read this guide and edit the JSON.',
    '',
    'Sizing, learned the hard way: mInitialSize multiplies the source image, it is not a pixel size. With a 44x44',
    'sprite a value of 0.3 gives 13-pixel specks that read as invisible on a busy background. Start at 1.0, and change',
    'the emission rate or the lifetime before you reach for the size.',
    '',
    'Emitter fields and their defaults: mEmitParticlesPerSecond (10), mParticlesLifetime (0.5) and',
    'mParticlesLifetimeRange (0), mEmissionDuration (0.1 - how long one emission burst lasts), mInitialSpeed (10) and',
    'mInitialSpeedRange, mInitialAngle (0) and mInitialAngleRange (45, degrees - the spread of the emission direction),',
    'mInitialSize (1) and mInitialSizeRange (0.3), mInitialAngleSpeed and mInitialAngleSpeedRange, mParticlesNumLimit',
    '(100, the hard cap on live particles), mEmittingCoefficient (1), mIsParticlesRelative (true - particles follow the',
    'emitter; set false so sparks stay where they were born), mPrewarmTime, mIs3D (false).',
    '',
    'Three sub-objects are polymorphic, i.e. {"Type": <class>, "Value": {...}}:',
    '- mParticlesSource - what a particle looks like. o2::SingleSpriteParticleSource has one field image, an asset ref:',
    '    "mParticlesSource": {"Type": "o2::SingleSpriteParticleSource", "Value": {"image": {"path": "Particles/dot.png"}}}',
    '  o2::MultiSpriteParticleSource takes an images array instead. The project already ships particle sprites in',
    '  Assets/Particles (dot.png, dot_soft.png, big_star.png, adot.png, backlight.png and more - list the folder).',
    '- mShape - where particles are born: o2::CircleParticlesEmitterShape, o2::SquareParticlesEmitterShape,',
    '  o2::SphereParticlesEmitterShape. The shape takes its size from the actor transform, and mEmitParticlesFromShell',
    '  makes them appear on its outline instead of inside it.',
    '- mEffects - an array of per-particle modifiers, each polymorphic:',
    '    o2::ParticlesGravityEffect  - field mGravity, a Vec3F, e.g. {"x": 0.0, "y": -400.0, "z": 0.0} to make sparks fall',
    '    o2::ParticlesColorEffect    - field colorGradient, tints particles over their life (use it to fade out)',
    '    o2::ParticlesRandomColorEffect - fields colorGradientA and colorGradientB, each particle picks between them',
    '    o2::ParticlesSizeEffect, o2::ParticlesAngleEffect, o2::ParticlesAngleSpeedEffect',
    '  A ColorGradient serializes as mKeys, an array of {"uid": <number>, "color": {"r","g","b","a"}, "position": <0..1>};',
    '  put alpha 255 at position 0 and alpha 0 at position 1 for a fade-out.',
    '',
    'A component entry therefore looks like this inside an actor:',
    '  {"Type": "o2::ParticlesEmitterComponent", "Data": {"mId": <fresh unique number>,',
    '    "mEmitParticlesPerSecond": 40.0, "mParticlesLifetime": 1.5, "mInitialSpeed": 300.0,',
    '    "mInitialAngleRange": 360.0, "mIsParticlesRelative": false, "mParticlesNumLimit": 300,',
    '    "mParticlesSource": {"Type": "o2::SingleSpriteParticleSource", "Value": {"image": {"path": "Particles/dot.png"}}},',
    '    "mShape": {"Type": "o2::CircleParticlesEmitterShape", "Value": {}},',
    '    "mEffects": [{"Type": "o2::ParticlesGravityEffect", "Value": {"mGravity": {"x": 0.0, "y": -400.0, "z": 0.0}}}]}}',
    '',
    'Driving it from JS: the emitter class is bound (new o2.ParticlesEmitterComponent()), and a script can add it with',
    'this._actor.AddComponent(...) or fetch an existing one with GetComponent("o2::ParticlesEmitterComponent"). Use a',
    'script when the effect must be dynamic - e.g. a firework that bursts at a new random point every second: keep an',
    'emitter actor, move it with GetTransform().SetPosition2D(...) and re-trigger emission in Update(dt). Note that only',
    'the fields marked @SCRIPTABLE are reachable from JS; check the header before relying on a setter, and configure',
    'anything static in the prototype JSON instead.',
    '',
    'Particles only move while the scene is running, so verify with play_mode({on:true}), a screenshot, then',
    'play_mode({on:false}). Nothing animates in edit mode.',
    '',
    'How to actually see your effect: a UI window prototype dropped into a scene draws nothing (widgets need the game\'s',
    'UI root), so do not judge it that way. Instead put the same emitter component on a plain o2::Actor in a scratch',
    'scene - write Assets/__check.scn with one actor at position 0,0 carrying your emitter, rebuild_assets,',
    'open_scene({path:"__check.scn"}), play_mode({on:true}), screenshot. Particles show up in the Scene view. Delete the',
    'scratch scene when you are done.',
    '',
    'Deeper detail: o2/Framework/Sources/o2/Render/Particles/ParticlesEmitter.h (every field with its default),',
    'ParticlesEffects.h (the effect classes), ParticlesEmitterShapes.h, ParticlesContainer.h (the sources).',
].join('\n');
